version: '3'

services:
  postgres:
    image: "${DB_IMAGE}"
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_HOST: $DB_HOST
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
