# Generated by Django 4.1.4 on 2022-12-19 14:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'image_storage',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Dog'), (2, 'Cat')], default=0)),
                ('user_id', models.UUIDField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_markup.imagetable')),
            ],
            options={
                'db_table': 'image_label',
            },
        ),
    ]
