# Generated by Django 4.1.4 on 2022-12-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_markup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='unique image label',
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('image',), name='unique image'),
        ),
    ]
